on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm publish --registry https://token:${{ secrets.GITHUB_TOKEN }}@npm.pkg.github.com

  install:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir ~/.ssh
        echo "${{ secrets.SECRET_PRIVATE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - run: npx jcansdale/private-npm-package#1.0.2
